# Generated by Django 5.2.5 on 2025-08-29 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Programa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("INACTIVO", "Inactivo"),
                            ("EN_REVISION", "En revisión"),
                            ("CERRADO", "Cerrado"),
                        ],
                        default="ACTIVO",
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Materia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("profesor", models.CharField(max_length=100)),
                (
                    "programa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materias",
                        to="estudiantes.programa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("edad", models.IntegerField()),
                (
                    "materias",
                    models.ManyToManyField(
                        related_name="estudiantes", to="estudiantes.materia"
                    ),
                ),
                (
                    "programa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estudiantes.programa",
                    ),
                ),
            ],
        ),
    ]
